server:
    port: 8080

spring:
    application:
      name: gateway
    main:
        allow-circular-references: true

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/registry/eureka
        fetch-registry: true

zuul:
    host:
        connect-timeout-millis: 1000
        socket-timeout-millis: 60000
    routes:
        loja-api:
            path: /loja-api/**
            url: http://localhost:8082
            service-id: loja-api
        catalogo-api:
            path: /catalogo-api/**
            url: http://localhost:8083
            service-id: catalogo-api
        transportadora-api:
            path: /transportadora-api/**
            url: http://localhost:8084
            service-id: transportadora-api