server:
  port: 8082
spring:
  application:
    name: loja-api
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loja-db?createDatabaseIfNotExist=true&useSSL=false
    username: admin
    password: 123qwe!!

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/registry/eureka

ribbon:
  eureka:
    enabled: false

loja-api:
  ribbon:
    listOfServers: localhost:8082