server:
  port: 8081
  servlet:
    context-path: /registry

spring:
  application:
    name: registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/registry/eureka/
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5